language: java

jdk: oraclejdk8
env: 
  global: ORG_GRADLE_PROJECT_downloadIdeaSources=false 
  matrix:
        - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
        - ORG_GRADLE_PROJECT_ideaVersion=15.0.4

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/